### ISSUE TITLE
FakeSound baord

### ISSUE THREAD

**Issue by Oi-jojo** [genesis-app/genesis#1]
Hi, 
sorry that im contacting you like this but how exactly does the fake soundbaord work? https://codeberg.org/Lunaa/userPlugins/src/branch/main/soundboard.web.ts
i tried using it in my server and it didnt work,
is it supposed to give me access to sounds in all the servers that im in?
Thank you and have a good day!

**Comment by aenriii** [comment]
bro this is nowhere near the place to ask this, ask @index.tsx on discord

**Comment by Oi-jojo** [comment]
> bro this is nowhere near the place to ask this, ask @index.tsx on discord

ye will do, have a good day
